config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount Heartcheck::App.new, at: '/monitoring'

  root 'home#index'

  get 'home/chart_data',               to: 'home#chart_data'
  get 'home/hire',                     to: 'home#hire'
  get 'home/contrato',                 to: 'home#contract'
  get 'home/representantes',           to: 'home#seller'
  get 'home/representantes/contratar', to: 'home#hire_seller'
  get 'home/representantes/contrato',  to: 'home#seller_contract'
  post 'home/representantes/create',   to: 'home#create_seller'

  get 'checkout/identificacao',                to: 'checkout#identification'
  get 'checkout/identificacao/assinante',      to: 'checkout#subscriber'
  get 'checkout/identificacao/novo_assinante', to: 'checkout#new_subscriber'
  get 'checkout/veiculos',                     to: 'checkout#vehicles'
  get 'checkout/resumo',                       to: 'checkout#resume'
  get 'checkout/subscriber_address',           to: 'checkout#subscriber_address'
  get 'checkout/check_seller',                 to: 'checkout#check_seller'
  get 'checkout/user_availability',            to: 'checkout#user_availability'
  get 'checkout/subscriber_ip',                to: 'checkout#subscriber_ip'
  get 'checkout/vehicle_model_list',           to: 'checkout#vehicle_model_list'
  get 'checkout/add_vehicles',                 to: 'checkout#add_vehicles'
  get 'checkout/pagamento',                    to: 'checkout#payment'
  get 'checkout/finalizacao',                  to: 'checkout#finalization'
  get 'checkout/remove_vehicles',              to: 'checkout#remove_vehicles'
  post 'checkout/subscriber_info',             to: 'checkout#subscriber_info'
  post 'checkout/process_payment',             to: 'checkout#process_payment'
  post 'checkout/find_subscriber_data',        to: 'checkout#find_subscriber_data'

  get 'login/assinantes',                         to: 'subscriber_logins#index'
  get 'login/assinantes/esqueci_minha_senha',     to: 'subscriber_logins#forgot_my_password'
  get 'login/representantes',                     to: 'seller_logins#index'
  get 'login/representantes/esqueci_minha_senha', to: 'seller_logins#forgot_my_password'
  post 'login/assinantes/validate_access',        to: 'subscriber_logins#validate_subscriber_access'
  post 'login/assinantes/send_password',          to: 'subscriber_logins#send_subscriber_password'
  post 'login/representantes/validate_access',    to: 'seller_logins#validate_seller_access'
  post 'login/representantes/send_password',      to: 'seller_logins#send_seller_password'

  get 'dashboards/assinantes',                  to: 'dashboards/subscribers/main#index'
  get 'dashboards/assinantes/logout',           to: 'dashboards/subscribers/main#logout'

  get 'dashboards/assinantes/angels/',          to: 'dashboards/subscribers/angels#index'
  get 'dashboards/assinantes/angels/adicionar', to: 'dashboards/subscribers/angels#insert'
  get 'dashboards/assinantes/angels/editar',    to: 'dashboards/subscribers/angels#edit'
  post 'dashboards/assinantes/angels/create',   to: 'dashboards/subscribers/angels#create'
  put 'dashboards/assinantes/angels/update',    to: 'dashboards/subscribers/angels#update'
  delete 'dashboards/assinantes/angels/remove', to: 'dashboards/subscribers/angels#remove'

  get 'dashboards/assinantes/chamados',                    to: 'dashboards/subscribers/tickets#index'
  get 'dashboards/assinantes/chamados/novo',               to: 'dashboards/subscribers/tickets#new'
  get 'dashboards/assinantes/chamados/:ticket_id',         to: 'dashboards/subscribers/tickets#show', as: 'show_ticket'
  get 'dashboards/assinantes/chamados/:ticket_id/editar',  to: 'dashboards/subscribers/tickets#edit', as: 'edit_ticket'
  post 'dashboards/assinantes/chamados/create',            to: 'dashboards/subscribers/tickets#create'
  post 'dashboards/assinantes/chamados/reopen/:ticket_id', to: 'dashboards/subscribers/tickets#reopen', as: 'reopen_ticket'

  get 'dashboards/assinantes/monitoramento', to: 'dashboards/subscribers/monitoring#index'

  get 'dashboards/assinantes/motoristas',                      to: 'dashboards/subscribers/drivers#index'
  get 'dashboards/assinantes/motoristas/adicionar',            to: 'dashboards/subscribers/drivers#insert'
  get 'dashboards/assinantes/motoristas/:driver_id/detalhes',  to: 'dashboards/subscribers/drivers#details', as: 'driver_details'
  get 'dashboards/assinantes/motoristas/:driver_id/editar',    to: 'dashboards/subscribers/drivers#edit', as: 'edit_driver'
  post 'dashboards/assinantes/motoristas/create',              to: 'dashboards/subscribers/drivers#create'
  put 'dashboards/assinantes/motoristas/update',               to: 'dashboards/subscribers/drivers#update'
  delete 'dashboards/assinantes/motoristas/:driver_id/remove', to: 'dashboards/subscribers/drivers#remove', as: 'remove_driver'

  get 'dashboards/assinantes/veiculos',                             to: 'dashboards/subscribers/vehicles#index'
  get 'dashboards/assinantes/veiculos/:vehicle_id/adicionar_fotos', to: 'dashboards/subscribers/vehicles#add_photos', as: 'add_vehicle_photos'
  get 'dashboards/assinantes/veiculos/:vehicle_id/detalhes',        to: 'dashboards/subscribers/vehicles#details', as: 'vehicle_details'
  post 'dashboards/assinantes/veiculos/upload_photos',              to: 'dashboards/subscribers/vehicles#upload_photos'

  get 'dashboards/assinantes/informacoes_pessoais',          to: 'dashboards/subscribers/informations/main#index'

  get 'dashboards/assinantes/informacoes_pessoais/cadastro',        to: 'dashboards/subscribers/informations/register#index'
  get 'dashboards/assinantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/subscribers/informations/register#edit'
  put 'dashboards/assinantes/informacoes_pessoais/cadastro/update', to: 'dashboards/subscribers/informations/register#update'

  get 'dashboards/assinantes/informacoes_pessoais/documentos',          to: 'dashboards/subscribers/informations/documents#index'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/subscribers/informations/documents#contract'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/subscribers/informations/documents#distract'

  get 'dashboards/representantes',        to: 'dashboards/sellers/main#index'
  get 'dashboards/representantes/logout', to: 'dashboards/sellers/main#logout'

  get 'dashboards/representantes/informacoes_pessoais',                 to: 'dashboards/sellers/informations/main#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro',        to: 'dashboards/sellers/informations/register#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/sellers/informations/register#edit'
  put 'dashboards/representantes/informacoes_pessoais/cadastro/update', to: 'dashboards/sellers/informations/register#update'

  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios',           to: 'dashboards/sellers/informations/banking#index'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/editar',    to: 'dashboards/sellers/informations/banking#edit'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/adicionar', to: 'dashboards/sellers/informations/banking#insert'
  post 'dashboards/representantes/informacoes_pessoais/dados_bancarios/create',   to: 'dashboards/sellers/informations/banking#create'
  put 'dashboards/representantes/informacoes_pessoais/dados_bancarios/update',    to: 'dashboards/sellers/informations/banking#update'

  get 'dashboards/representantes/informacoes_pessoais/documentos',          to: 'dashboards/sellers/informations/documents#index'
  get 'dashboards/representantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/sellers/informations/documents#contract'
  get 'dashboards/representantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/sellers/informations/documents#distract'

  get 'dashboards/representantes/financeiro',        to: 'dashboards/sellers/finance/main#index'

  get 'dashboards/representantes/financeiro/vendas', to: 'dashboards/sellers/finance/sales#index'

  get 'dashboards/representantes/financeiro/recibos',                            to: 'dashboards/sellers/finance/receipts#index'
  post 'dashboards/representantes/financeiro/recibos/recibo_pagamento_autonomo', to: 'dashboards/sellers/finance/receipts#generate_receipt'

  get 'cameras/logins',                             to: 'cameras/logins#index'
  get 'cameras/logins/angels',                      to: 'cameras/logins#angels'
  get 'cameras/logins/motoristas',                  to: 'cameras/logins#drivers'
  get 'cameras/logins/driver_names',                to: 'cameras/logins#driver_names'
  post 'cameras/logins/validate_angels_access',     to: 'cameras/logins#validate_angels_access'
  post 'cameras/logins/validate_drivers_access',    to: 'cameras/logins#validate_drivers_access'

  get 'cameras/dashboards/passageiros', to: 'cameras/dashboards#passengers'

  get 'cameras/dashboards/motoristas',             to: 'cameras/dashboards/drivers#index'
  get 'cameras/dashboards/motoristas/login',       to: 'cameras/dashboards/drivers#login'
  get 'cameras/dashboards/motoristas/logout',      to: 'cameras/dashboards/drivers#logout'
  get 'cameras/dashboards/motoristas/qrcode',      to: 'cameras/dashboards/drivers#qrcode'
  get 'cameras/dashboards/motoristas/transmissao', to: 'cameras/dashboards/drivers#transmission'

  get 'cameras/dashboards/angels',             to: 'cameras/dashboards/angels#index'
  get 'cameras/dashboards/angels/login',       to: 'cameras/dashboards/angels#login'
  get 'cameras/dashboards/angels/logout',      to: 'cameras/dashboards/angels#logout'
  get 'cameras/dashboards/angels/transmissao', to: 'cameras/dashboards/angels#transmission'

app/controllers/dashboards/subscribers/angels_controller.rb
class Dashboards::Subscribers::AngelsController < ApplicationController
  before_action :validate_sessions
  before_action :find_subscriber

  def index; end

  def insert
    @angel = Angel.new
  end

  def edit
    @angel = @subscriber.angels.detect { |angel| angel.id == params['angel'].to_i }
 
    unless @angel.present?
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.search_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.search_data_failed')
  end

  def remove
    angel = @subscriber.angels.detect { |angel| angel.id == params['angel'].to_i }

    if angel.present?
      angel.delete

      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.remove_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.remove_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.remove_data_failed')
  end

  def update
    angel = @subscriber.angels.detect { |angel| angel.id == params['angel_id'].to_i }

    if angel.update_attributes!(angel_params)
      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.update_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.save_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.save_data_failed')
  end

  def create
    angel = Angel.new(angel_params)

    if angel.valid?
      angel.save!

      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.save_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.save_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.save_data_failed')
  end

  private

    def angel_params
      params
        .require(:angel)
        .permit(:name, :cpf, :status)
        .merge!({ subscriber: @subscriber })
    end
end

app/controllers/dashboards/subscribers/drivers_controller.rb
class Dashboards::Subscribers::DriversController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index
    @drivers = @subscriber.drivers
  end

  def insert
    @vehicles_list = @subscriber.vehicles.pluck(:license_plate)
    @driver = Driver.new
  end

  def remove
    if driver
      Driver.delete(driver.id)

      redirect_to dashboards_assinantes_motoristas_path,
                  notice: t('messages.successes.remove_data')
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.remove_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.remove_data_failed')
  end

  def edit
    @vehicles_list = @subscriber.vehicles.pluck(:license_plate)

    if driver
      @driver = driver
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.search_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.show_data_failed')
  end

  def details
    if driver
      @driver = driver
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.search_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.show_data_failed')
  end

  def create
    driver = Driver.new(driver_params)
    driver.code = driver.generate_code

    if driver.valid? && driver.save!
      driver.update_attributes!(vehicles: vehicles_list)
      driver.document.attach(driver_params['document'])
      driver.avatar.attach(driver_params['avatar'])

      redirect_to driver_details_path(driver.id),
                  notice: t('messages.successes.save_data')
    else
      redirect_to dashboards_assinantes_motoristas_adicionar_path,
                  alert: t('messages.errors.save_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_adicionar_path,
                alert: t('messages.errors.save_data_failed')
  end

  def update
    driver_data = driver

    if driver_data.update_attributes!(driver_params)
      driver_data.update_attributes!(vehicles: vehicles_list) if driver_params['vehicle_license_plates']
      driver_data.document.attach(driver_params['document']) if driver_params['document']
      driver_data.avatar.attach(driver_params['avatar']) if driver_params['avatar']

      redirect_to driver_details_path(driver_data.id),
                  notice: t('messages.successes.update_data')
    else
      redirect_to edit_driver_path(driver_data.id),
                  alert: t('messages.errors.update_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.update_data_failed')
  end

  private

    def vehicles_list
      params['driver']['vehicle_license_plates']
        .reject(&:blank?)
        .map { |license_plate| Vehicle.find_by_license_plate(license_plate) }
    end

    def driver
      driver_id = params['driver_id'] || driver_params[:id] || params['driver']['driver_id']

      driver ||= @subscriber
                   .drivers
                   .detect { |driver| driver.id.to_s == driver_id }
    end

    def driver_params
      params
        .require(:driver)
        .permit(:vehicle_license_plates,
                :name,
                :license,
                :paid_activity,
                :expedition_date,
                :expiration_date,
                :document,
                :avatar)
    end
end

app/controllers/dashboards/subscribers/informations/documents_controller.rb
class Dashboards::Subscribers::Informations::DocumentsController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index;end

  def contract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.subscriber.contract.title'),
                             template: 'dashboards/subscribers/informations/documents/contract.html.erb',
                             layout: 'subscriber_contract.html')
      end
    end
  end

  def distract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.subscriber.distract.title'),
                             template: 'dashboards/subscribers/informations/documents/distract.html.erb',
                             layout: 'subscriber_distract.html')
      end
    end
  end
end

app/controllers/dashboards/subscribers/informations/main_controller.rb
class Dashboards::Subscribers::Informations::MainController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index; end
end

app/helpers/dashboards/subscribers_helper.rb
module Dashboards::SubscribersHelper
  def drivers_name(vehicle)
    vehicle
      .drivers
      .pluck(:name)
      .sort
      .join(' | ') 
  end
end

app/views/dashboards/subscribers/vehicles/add_photos.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.vehicles'), dashboards_assinantes_veiculos_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.add_photos') %>
      </li>
    </ol>
  </nav>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <h3>
      <b><%= t('.license_plate', license_plate: @vehicle.license_plate) %></b>
    </h3>
    <hr>
    <%= form_with scope: 'vehicle', url: dashboards_assinantes_veiculos_upload_photos_path do |f| %>
      <div class="form-group">
        <label><%= t('.vehicle_photo') %></label>
        <%= f.file_field :photos,
                         multiple: true,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <br>
      <%= f.submit t('.send_photos_btn'),
                   class: 'btn btn-primary btn-sm' %>

      <%= f.hidden_field :id, value: @vehicle.id %>
    <% end %>
  </div>
</div>
<%= render './././partials/footer' %>

app/views/dashboards/subscribers/vehicles/details.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.vehicles'), dashboards_assinantes_veiculos_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.details') %>
      </li>
    </ol>
  </nav>
  <% unless @vehicle.have_photos? %>
    <div class="alert alert-warning" role="alert">
      <%= t('messages.warning.vehicle_photos_missing') %>
    </div>
  <% end %>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <h4>
      <b><%= t('.vehicle_details') %></b>
    </h4>
    <hr>
    <div class="form-group form-check">
      <b><span><%= t('.brand') %></span></b>
      <%= @vehicle.brand %>
    </div>
    <div class="form-group form-check">
      <b><span><%= t('.kind') %></span></b>
      <%= @vehicle.kind %>
    </div>
    <div class="form-group form-check">
      <b><span><%= t('.license_plate') %></span></b>
      <%= @vehicle.license_plate %>
    </div>
    <div class="form-group form-check">
      <b><span><%= t('.photos') %></span></b>
      <br><br>
      <% @vehicle.photos.each do |photo| %>
        <%= image_tag photo, class: 'photos' %>
        <hr>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<%= render './././partials/footer' %>

app/views/dashboards/subscribers/vehicles/index.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.vehicles') %>
      </li>
    </ol>
  </nav>
  <%= render './././partials/photos_missing' %>
  <h4>
    <b><%= t('.vehicles') %></b>
  </h4>
    <table class="table">
      <thead>
        <th><%= t('.brand') %></th>
        <th><%= t('.kind') %></th>
        <th><%= t('.license_plate') %></th>
        <th><%= t('.status') %></th>
        <th></th>
      </thead>
    <% @subscriber.vehicles.sort_by_license_plate.each do |vehicle| %>
      <tr>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.kind %></td>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.status %></td>
        <td>
          <%= link_to vehicle_details_path(vehicle.id) do %>
            <i class='material-icons'>view_headline</i>
          <% end %>
          <%= link_to add_vehicle_photos_path(vehicle.id) do %>
            <i class='material-icons'>add_a_photo</i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
<%= render './././partials/footer' %>