config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount Heartcheck::App.new, at: '/monitoring'

  root 'home#index'

  get 'home/chart_data',               to: 'home#chart_data'
  get 'home/hire',                     to: 'home#hire'
  get 'home/contrato',                 to: 'home#contract'
  get 'home/representantes',           to: 'home#seller'
  get 'home/representantes/contratar', to: 'home#hire_seller'
  get 'home/representantes/contrato',  to: 'home#seller_contract'
  post 'home/representantes/create',   to: 'home#create_seller'

  get 'checkout/identificacao',                to: 'checkout#identification'
  get 'checkout/identificacao/assinante',      to: 'checkout#subscriber'
  get 'checkout/identificacao/novo_assinante', to: 'checkout#new_subscriber'
  get 'checkout/veiculos',                     to: 'checkout#vehicles'
  get 'checkout/resumo',                       to: 'checkout#resume'
  get 'checkout/subscriber_address',           to: 'checkout#subscriber_address'
  get 'checkout/check_seller',                 to: 'checkout#check_seller'
  get 'checkout/user_availability',            to: 'checkout#user_availability'
  get 'checkout/subscriber_ip',                to: 'checkout#subscriber_ip'
  get 'checkout/vehicle_model_list',           to: 'checkout#vehicle_model_list'
  get 'checkout/add_vehicles',                 to: 'checkout#add_vehicles'
  get 'checkout/pagamento',                    to: 'checkout#payment'
  get 'checkout/finalizacao',                  to: 'checkout#finalization'
  get 'checkout/remove_vehicles',              to: 'checkout#remove_vehicles'
  post 'checkout/subscriber_info',             to: 'checkout#subscriber_info'
  post 'checkout/process_payment',             to: 'checkout#process_payment'
  post 'checkout/find_subscriber_data',        to: 'checkout#find_subscriber_data'

  get 'login/assinantes',                         to: 'subscriber_logins#index'
  get 'login/assinantes/esqueci_minha_senha',     to: 'subscriber_logins#forgot_my_password'
  get 'login/representantes',                     to: 'seller_logins#index'
  get 'login/representantes/esqueci_minha_senha', to: 'seller_logins#forgot_my_password'
  post 'login/assinantes/validate_access',        to: 'subscriber_logins#validate_subscriber_access'
  post 'login/assinantes/send_password',          to: 'subscriber_logins#send_subscriber_password'
  post 'login/representantes/validate_access',    to: 'seller_logins#validate_seller_access'
  post 'login/representantes/send_password',      to: 'seller_logins#send_seller_password'

  get 'dashboards/assinantes',                  to: 'dashboards/subscribers/main#index'
  get 'dashboards/assinantes/logout',           to: 'dashboards/subscribers/main#logout'

  get 'dashboards/assinantes/angels/',          to: 'dashboards/subscribers/angels#index'
  get 'dashboards/assinantes/angels/adicionar', to: 'dashboards/subscribers/angels#insert'
  get 'dashboards/assinantes/angels/editar',    to: 'dashboards/subscribers/angels#edit'
  post 'dashboards/assinantes/angels/create',   to: 'dashboards/subscribers/angels#create'
  put 'dashboards/assinantes/angels/update',    to: 'dashboards/subscribers/angels#update'
  delete 'dashboards/assinantes/angels/remove', to: 'dashboards/subscribers/angels#remove'

  get 'dashboards/assinantes/chamados',                    to: 'dashboards/subscribers/tickets#index'
  get 'dashboards/assinantes/chamados/novo',               to: 'dashboards/subscribers/tickets#new'
  get 'dashboards/assinantes/chamados/:ticket_id',         to: 'dashboards/subscribers/tickets#show', as: 'show_ticket'
  get 'dashboards/assinantes/chamados/:ticket_id/editar',  to: 'dashboards/subscribers/tickets#edit', as: 'edit_ticket'
  post 'dashboards/assinantes/chamados/create',            to: 'dashboards/subscribers/tickets#create'
  post 'dashboards/assinantes/chamados/reopen/:ticket_id', to: 'dashboards/subscribers/tickets#reopen', as: 'reopen_ticket'

  get 'dashboards/assinantes/monitoramento', to: 'dashboards/subscribers/monitoring#index'

  get 'dashboards/assinantes/motoristas',                      to: 'dashboards/subscribers/drivers#index'
  get 'dashboards/assinantes/motoristas/adicionar',            to: 'dashboards/subscribers/drivers#insert'
  get 'dashboards/assinantes/motoristas/:driver_id/detalhes',  to: 'dashboards/subscribers/drivers#details', as: 'driver_details'
  get 'dashboards/assinantes/motoristas/:driver_id/editar',    to: 'dashboards/subscribers/drivers#edit', as: 'edit_driver'
  post 'dashboards/assinantes/motoristas/create',              to: 'dashboards/subscribers/drivers#create'
  put 'dashboards/assinantes/motoristas/update',               to: 'dashboards/subscribers/drivers#update'
  delete 'dashboards/assinantes/motoristas/:driver_id/remove', to: 'dashboards/subscribers/drivers#remove', as: 'remove_driver'

  get 'dashboards/assinantes/veiculos',                             to: 'dashboards/subscribers/vehicles#index'
  get 'dashboards/assinantes/veiculos/:vehicle_id/adicionar_fotos', to: 'dashboards/subscribers/vehicles#add_photos', as: 'add_vehicle_photos'
  get 'dashboards/assinantes/veiculos/:vehicle_id/detalhes',        to: 'dashboards/subscribers/vehicles#details', as: 'vehicle_details'
  post 'dashboards/assinantes/veiculos/upload_photos',              to: 'dashboards/subscribers/vehicles#upload_photos'

  get 'dashboards/assinantes/informacoes_pessoais',          to: 'dashboards/subscribers/informations/main#index'

  get 'dashboards/assinantes/informacoes_pessoais/cadastro',        to: 'dashboards/subscribers/informations/register#index'
  get 'dashboards/assinantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/subscribers/informations/register#edit'
  put 'dashboards/assinantes/informacoes_pessoais/cadastro/update', to: 'dashboards/subscribers/informations/register#update'

  get 'dashboards/assinantes/informacoes_pessoais/documentos',          to: 'dashboards/subscribers/informations/documents#index'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/subscribers/informations/documents#contract'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/subscribers/informations/documents#distract'

  get 'dashboards/representantes',        to: 'dashboards/sellers/main#index'
  get 'dashboards/representantes/logout', to: 'dashboards/sellers/main#logout'

  get 'dashboards/representantes/informacoes_pessoais',                 to: 'dashboards/sellers/informations/main#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro',        to: 'dashboards/sellers/informations/register#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/sellers/informations/register#edit'
  put 'dashboards/representantes/informacoes_pessoais/cadastro/update', to: 'dashboards/sellers/informations/register#update'

  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios',           to: 'dashboards/sellers/informations/banking#index'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/editar',    to: 'dashboards/sellers/informations/banking#edit'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/adicionar', to: 'dashboards/sellers/informations/banking#insert'
  post 'dashboards/representantes/informacoes_pessoais/dados_bancarios/create',   to: 'dashboards/sellers/informations/banking#create'
  put 'dashboards/representantes/informacoes_pessoais/dados_bancarios/update',    to: 'dashboards/sellers/informations/banking#update'

  get 'dashboards/representantes/informacoes_pessoais/documentos',          to: 'dashboards/sellers/informations/documents#index'
  get 'dashboards/representantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/sellers/informations/documents#contract'
  get 'dashboards/representantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/sellers/informations/documents#distract'

  get 'dashboards/representantes/financeiro',        to: 'dashboards/sellers/finance/main#index'

  get 'dashboards/representantes/financeiro/vendas', to: 'dashboards/sellers/finance/sales#index'

  get 'dashboards/representantes/financeiro/recibos',                            to: 'dashboards/sellers/finance/receipts#index'
  post 'dashboards/representantes/financeiro/recibos/recibo_pagamento_autonomo', to: 'dashboards/sellers/finance/receipts#generate_receipt'

  get 'cameras/logins',                             to: 'cameras/logins#index'
  get 'cameras/logins/angels',                      to: 'cameras/logins#angels'
  get 'cameras/logins/motoristas',                  to: 'cameras/logins#drivers'
  get 'cameras/logins/driver_names',                to: 'cameras/logins#driver_names'
  post 'cameras/logins/validate_angels_access',     to: 'cameras/logins#validate_angels_access'
  post 'cameras/logins/validate_drivers_access',    to: 'cameras/logins#validate_drivers_access'

  get 'cameras/dashboards/passageiros', to: 'cameras/dashboards#passengers'

  get 'cameras/dashboards/motoristas',             to: 'cameras/dashboards/drivers#index'
  get 'cameras/dashboards/motoristas/login',       to: 'cameras/dashboards/drivers#login'
  get 'cameras/dashboards/motoristas/logout',      to: 'cameras/dashboards/drivers#logout'
  get 'cameras/dashboards/motoristas/qrcode',      to: 'cameras/dashboards/drivers#qrcode'
  get 'cameras/dashboards/motoristas/transmissao', to: 'cameras/dashboards/drivers#transmission'

  get 'cameras/dashboards/angels',             to: 'cameras/dashboards/angels#index'
  get 'cameras/dashboards/angels/login',       to: 'cameras/dashboards/angels#login'
  get 'cameras/dashboards/angels/logout',      to: 'cameras/dashboards/angels#logout'
  get 'cameras/dashboards/angels/transmissao', to: 'cameras/dashboards/angels#transmission'
  get 'cameras/dashboards/angels/motorista',      to: 'cameras/dashboards/angels#driver'

app/controllers/dashboards/sellers/informations/banking_controller.rb
class Dashboards::Sellers::Informations::BankingController < ApplicationController
  before_action :validate_seller_session, :find_seller

  def index; end
  def edit; end

  def create
    bank = Bank.find_by_compe_register(seller_params[:bank])

    account = Account
                .new(agency: seller_params[:agency],
                     number: seller_params[:account],
                     seller: @seller,
                     bank: bank)

    if account.valid? && account.save!
      redirect_to dashboards_representantes_informacoes_pessoais_dados_bancarios_path,
                  notice: t('messages.successes.save_data')
    else
      redirect_to dashboards_representantes_informacoes_pessoais_dados_bancarios_path,
                  alert: t('messages.errors.save_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_representantes_informacoes_pessoais_dados_bancarios_path,
                alert: t('messages.errors.save_data_failed')
  end

  def update
    ActiveRecord::Base.transaction do
      bank = Bank.find_by_compe_register(seller_params[:bank])
      @seller.bank = bank
      @seller.save!

      account = @seller.account
      account.agency = seller_params[:agency]
      account.number = seller_params[:account]
      account.save!
    end

    redirect_to dashboards_representantes_informacoes_pessoais_dados_bancarios_path,
                notice: t('messages.successes.update_data')
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_representantes_informacoes_pessoais_dados_bancarios_path,
                alert: t('messages.errors.update_data_failed')
  end

  private

  def seller_params
    params.require(:seller).permit(:bank, :agency, :account)
  end
end

app/controllers/dashboards/sellers/informations/documents_controller.rb
class Dashboards::Sellers::Informations::DocumentsController < ApplicationController
  before_action :validate_seller_session, :find_seller

  def index; end

  def contract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.seller.contract.title'),
                             template: 'dashboards/sellers/informations/documents/contract.html.erb',
                             layout: 'seller_contract.html')
      end
    end
  end

  def distract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.seller.distract.title'),
                             template: 'dashboards/sellers/informations/documents/distract.html.erb',
                             layout: 'seller_distract.html')
      end
    end
  end
end

app/controllers/dashboards/sellers/informations/main_controller.rb
class Dashboards::Sellers::Informations::MainController < ApplicationController
  before_action :validate_seller_session, :find_seller

  def index; end
end

app/controllers/dashboards/sellers/informations/register_controller.rb
class Dashboards::Sellers::Informations::RegisterController < ApplicationController
  before_action :validate_seller_session, :find_seller

  def index; end
  def edit; end

  def update
    seller = Seller.find_by_code(session[:seller_code])

    message = if seller.update_attributes!(seller_params)
                { notice: t('messages.successes.update_data') }
              else
                { alert: t('messages.errors.update_data_failed') }
              end

    redirect_to dashboards_representantes_informacoes_pessoais_cadastro_path, message
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_representantes_informacoes_pessoais_cadastro_path,
                alert: t('messages.errors.update_data_failed')
  end

  private

    def seller_params
      params
        .require(:seller)
        .permit(:name,
                :core_register,
                :expedition_date,
                :expiration_date,
                :cellphone,
                :email,
                :address,
                :number,
                :complement,
                :district,
                :city,
                :state,
                :linkedin,
                :postal_code)
   end
end

app/controllers/dashboards/subscribers/informations/documents_controller.rb
class Dashboards::Subscribers::Informations::DocumentsController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index;end

  def contract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.subscriber.contract.title'),
                             template: 'dashboards/subscribers/informations/documents/contract.html.erb',
                             layout: 'subscriber_contract.html')
      end
    end
  end

  def distract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.subscriber.distract.title'),
                             template: 'dashboards/subscribers/informations/documents/distract.html.erb',
                             layout: 'subscriber_distract.html')
      end
    end
  end
end

app/controllers/dashboards/subscribers/informations/main_controller.rb
class Dashboards::Subscribers::Informations::MainController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index; end
end

app/controllers/dashboards/subscribers/informations/register_controller.rb
class Dashboards::Subscribers::Informations::RegisterController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index; end
  def edit; end

  def update
    @subscriber.assign_attributes(subscriber_params)

    if @subscriber.valid? && update_payment_gateway_data!
      @subscriber.update_attributes!(subscriber_params)

      message = { notice: t('messages.successes.update_data') }
    else
      message = { alert: t('messages.errors.update_data_failed') }
    end

    redirect_to dashboards_assinantes_informacoes_pessoais_cadastro_path, message
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_informacoes_pessoais_cadastro_path,
                alert: t('messages.errors.update_data_failed')
  end

  private

  def update_payment_gateway_data!
    Gateways::Payment::Subscriber.update!(@subscriber)
  end

  def subscriber_params
    params
      .require(:subscriber)
      .permit(:responsible_name,
              :responsible_cpf,
              :postal_code,
              :address,
              :number,
              :complement,
              :district,
              :city,
              :state,
              :telephone,
              :cellphone)
      .merge('code' => session[:subscriber_code])
  end
end

app/helpers/dashboards/sellers/informations/banking_helper.rb
module Dashboards::Sellers::Informations::BankingHelper
  def bank_list
    Bank.all.map { |bank| ["#{bank.compe_register} - #{bank.name}", bank.compe_register] }
  end
end

app/views/dashboards/sellers/informations/banking/edit.html.erb
<%= render './././partials/header' %>                                                                                                                                                     
<%= render './././partials/logout' %>
<div class="container-fluid">
  <%= render './partials/messages' %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.dashboard'), dashboards_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.informations'), dashboards_representantes_informacoes_pessoais_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.banking'), dashboards_representantes_informacoes_pessoais_dados_bancarios_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.sellers.edit') %>
      </li>
    </ol>
  </nav>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <div>
      <h4 class="form-subtitle">
        <%= t('.subtitle') %>
      </h4>
    </div>
    <hr>
    <%= form_with scope: @seller, url: dashboards_representantes_informacoes_pessoais_dados_bancarios_create_path, method: :put do |f| %>
      <div class="form-group form-check">
        <b><span><%= t('.favored') %></span></b>
        <%= @seller.name %>
      </div>
      <div class="form-group form-check">
        <b><span><%= t('.document') %></span></b>
        <%= @seller.document %>
      </div>
      <div class="form-group">
        <label><%= t('.bank_name') %></label>
        <br>
        <%= f.select :bank,
                     options_for_select(bank_list,
                                        selected: @seller.bank.compe_register),
                     {},
                     class: 'form-control',
                     required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.agency') %></label>
        <%= f.text_field :agency,
                         value: @seller.account.agency,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.account') %></label>
        <%= f.text_field :account,
                         value: @seller.account.number,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <hr>
      <%= f.submit t('.update_data_btn'),
                   class: 'btn btn-primary small-fields' %>
    <% end %>
    <br>
    <br>
    <br>
  </div>
</div>
<%= render './././partials/footer' %>

app/views/dashboards/sellers/informations/banking/index.html.erb
<%= render './././partials/header' %>                                                                                                                                                     
<%= render './././partials/logout' %>
<div class="container-fluid">
  <%= render './partials/messages' %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.dashboard'), dashboards_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.informations'), dashboards_representantes_informacoes_pessoais_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.sellers.banking') %>
      </li> 
    </ol>
  </nav>
  <% unless @seller.account.present? %>
    <div class="alert alert-warning" role="alert">
      <%= t('messages.warning.seller_account_missing') %>
    </div>
  <% end %>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <% if @seller.account.present? %>
      <h4>
        <b>
          <%= t('.seller_code') %>
          <%= @seller.code %>
        </b>
      </h4>
      <hr>
      <div>
        <h4 class="form-subtitle">
          <%= t('.subtitle') %>
        </h4>
      </div>
      <hr>
      <div class="form-group form-check">
        <b><span><%= t('.bank_name') %></span></b>
        <%= @seller.bank.name %>
      </div>
      <div class="form-group form-check">
        <b><span><%= t('.bank_compe') %></span></b>
        <%= @seller.bank.compe_register %>
      </div>
      <div class="form-group form-check">
        <b><span><%= t('.agency') %></span></b>
        <%= @seller.account.agency %>
      </div>
      <div class="form-group form-check">
        <b><span><%= t('.number') %></span></b>
        <%= @seller.account.number %>
      </div>
      <hr>
      <%= link_to t('.edit_account_data_btn'),
                    dashboards_representantes_informacoes_pessoais_dados_bancarios_editar_path,
                    class: 'btn btn-primary short-fields' %>
    <% else %>
      <%= link_to t('.add_account_btn'),
                    dashboards_representantes_informacoes_pessoais_dados_bancarios_adicionar_path,
                    class: 'btn btn-primary short-fields' %>
    <% end%>
    <br>
    <br>
    <br>
  </div>
</div>
<%= render './././partials/footer' %>

app/views/dashboards/sellers/informations/banking/insert.html.erb
<%= render './././partials/header' %>                                                                                                                                                     
<%= render './././partials/logout' %>
<div class="container-fluid">
  <%= render './partials/messages' %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.dashboard'), dashboards_representantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.informations'), dashboards_representantes_informacoes_pessoais_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.sellers.banking'), dashboards_representantes_informacoes_pessoais_dados_bancarios_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.sellers.add_account') %>
      </li>
    </ol>
  </nav>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <div>
      <h4 class="form-subtitle">
        <%= t('.subtitle') %>
      </h4>
    </div>
    <hr>
    <%= form_with scope: 'seller' , url: dashboards_representantes_informacoes_pessoais_dados_bancarios_create_path, method: :post do |f| %>
      <div class="form-group form-check">
        <b><span><%= t('.favored') %></span></b>
        <%= @seller.name %>
      </div>
      <div class="form-group form-check">
        <b><span><%= t('.document') %></span></b>
        <%= @seller.document %>
      </div>
      <div class="form-group">
        <label><%= t('.bank_name') %></label>
        <br>
        <%= f.select :bank,
                     options_for_select(bank_list),
                     {},
                     class: 'form-control',
                     required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.agency') %></label>
        <%= f.text_field :agency,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.account') %></label>
        <%= f.text_field :account,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <hr>
      <%= f.submit t('.save_data_btn'),
                   class: 'btn btn-primary small-fields' %>
    <% end %>
    <br>
    <br>
    <br>
  </div>
</div>
<%= render './././partials/footer' %>