config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount Heartcheck::App.new, at: '/monitoring'

  root 'home#index'

  get 'home/chart_data',               to: 'home#chart_data'
  get 'home/hire',                     to: 'home#hire'
  get 'home/contrato',                 to: 'home#contract'
  get 'home/representantes',           to: 'home#seller'
  get 'home/representantes/contratar', to: 'home#hire_seller'
  get 'home/representantes/contrato',  to: 'home#seller_contract'
  post 'home/representantes/create',   to: 'home#create_seller'

  get 'checkout/identificacao',                to: 'checkout#identification'
  get 'checkout/identificacao/assinante',      to: 'checkout#subscriber'
  get 'checkout/identificacao/novo_assinante', to: 'checkout#new_subscriber'
  get 'checkout/veiculos',                     to: 'checkout#vehicles'
  get 'checkout/resumo',                       to: 'checkout#resume'
  get 'checkout/subscriber_address',           to: 'checkout#subscriber_address'
  get 'checkout/check_seller',                 to: 'checkout#check_seller'
  get 'checkout/user_availability',            to: 'checkout#user_availability'
  get 'checkout/subscriber_ip',                to: 'checkout#subscriber_ip'
  get 'checkout/vehicle_model_list',           to: 'checkout#vehicle_model_list'
  get 'checkout/add_vehicles',                 to: 'checkout#add_vehicles'
  get 'checkout/pagamento',                    to: 'checkout#payment'
  get 'checkout/finalizacao',                  to: 'checkout#finalization'
  get 'checkout/remove_vehicles',              to: 'checkout#remove_vehicles'
  post 'checkout/subscriber_info',             to: 'checkout#subscriber_info'
  post 'checkout/process_payment',             to: 'checkout#process_payment'
  post 'checkout/find_subscriber_data',        to: 'checkout#find_subscriber_data'

  get 'login/assinantes',                         to: 'subscriber_logins#index'
  get 'login/assinantes/esqueci_minha_senha',     to: 'subscriber_logins#forgot_my_password'
  get 'login/representantes',                     to: 'seller_logins#index'
  get 'login/representantes/esqueci_minha_senha', to: 'seller_logins#forgot_my_password'
  post 'login/assinantes/validate_access',        to: 'subscriber_logins#validate_subscriber_access'
  post 'login/assinantes/send_password',          to: 'subscriber_logins#send_subscriber_password'
  post 'login/representantes/validate_access',    to: 'seller_logins#validate_seller_access'
  post 'login/representantes/send_password',      to: 'seller_logins#send_seller_password'

  get 'dashboards/assinantes',                  to: 'dashboards/subscribers/main#index'
  get 'dashboards/assinantes/logout',           to: 'dashboards/subscribers/main#logout'

  get 'dashboards/assinantes/angels/',          to: 'dashboards/subscribers/angels#index'
  get 'dashboards/assinantes/angels/adicionar', to: 'dashboards/subscribers/angels#insert'
  get 'dashboards/assinantes/angels/editar',    to: 'dashboards/subscribers/angels#edit'
  post 'dashboards/assinantes/angels/create',   to: 'dashboards/subscribers/angels#create'
  put 'dashboards/assinantes/angels/update',    to: 'dashboards/subscribers/angels#update'
  delete 'dashboards/assinantes/angels/remove', to: 'dashboards/subscribers/angels#remove'

  get 'dashboards/assinantes/chamados',                    to: 'dashboards/subscribers/tickets#index'
  get 'dashboards/assinantes/chamados/novo',               to: 'dashboards/subscribers/tickets#new'
  get 'dashboards/assinantes/chamados/:ticket_id',         to: 'dashboards/subscribers/tickets#show', as: 'show_ticket'
  get 'dashboards/assinantes/chamados/:ticket_id/editar',  to: 'dashboards/subscribers/tickets#edit', as: 'edit_ticket'
  post 'dashboards/assinantes/chamados/create',            to: 'dashboards/subscribers/tickets#create'
  post 'dashboards/assinantes/chamados/reopen/:ticket_id', to: 'dashboards/subscribers/tickets#reopen', as: 'reopen_ticket'

  get 'dashboards/assinantes/monitoramento', to: 'dashboards/subscribers/monitoring#index'

  get 'dashboards/assinantes/motoristas',                      to: 'dashboards/subscribers/drivers#index'
  get 'dashboards/assinantes/motoristas/adicionar',            to: 'dashboards/subscribers/drivers#insert'
  get 'dashboards/assinantes/motoristas/:driver_id/detalhes',  to: 'dashboards/subscribers/drivers#details', as: 'driver_details'
  get 'dashboards/assinantes/motoristas/:driver_id/editar',    to: 'dashboards/subscribers/drivers#edit', as: 'edit_driver'
  post 'dashboards/assinantes/motoristas/create',              to: 'dashboards/subscribers/drivers#create'
  put 'dashboards/assinantes/motoristas/update',               to: 'dashboards/subscribers/drivers#update'
  delete 'dashboards/assinantes/motoristas/:driver_id/remove', to: 'dashboards/subscribers/drivers#remove', as: 'remove_driver'

  get 'dashboards/assinantes/veiculos',                             to: 'dashboards/subscribers/vehicles#index'
  get 'dashboards/assinantes/veiculos/:vehicle_id/adicionar_fotos', to: 'dashboards/subscribers/vehicles#add_photos', as: 'add_vehicle_photos'
  get 'dashboards/assinantes/veiculos/:vehicle_id/detalhes',        to: 'dashboards/subscribers/vehicles#details', as: 'vehicle_details'
  post 'dashboards/assinantes/veiculos/upload_photos',              to: 'dashboards/subscribers/vehicles#upload_photos'

  get 'dashboards/assinantes/informacoes_pessoais',          to: 'dashboards/subscribers/informations/main#index'

  get 'dashboards/assinantes/informacoes_pessoais/cadastro',        to: 'dashboards/subscribers/informations/register#index'
  get 'dashboards/assinantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/subscribers/informations/register#edit'
  put 'dashboards/assinantes/informacoes_pessoais/cadastro/update', to: 'dashboards/subscribers/informations/register#update'

  get 'dashboards/assinantes/informacoes_pessoais/documentos',          to: 'dashboards/subscribers/informations/documents#index'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/subscribers/informations/documents#contract'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/subscribers/informations/documents#distract'

  get 'dashboards/representantes',        to: 'dashboards/sellers/main#index'
  get 'dashboards/representantes/logout', to: 'dashboards/sellers/main#logout'

  get 'dashboards/representantes/informacoes_pessoais',                 to: 'dashboards/sellers/informations/main#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro',        to: 'dashboards/sellers/informations/register#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/sellers/informations/register#edit'
  put 'dashboards/representantes/informacoes_pessoais/cadastro/update', to: 'dashboards/sellers/informations/register#update'

  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios',           to: 'dashboards/sellers/informations/banking#index'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/editar',    to: 'dashboards/sellers/informations/banking#edit'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/adicionar', to: 'dashboards/sellers/informations/banking#insert'
  post 'dashboards/representantes/informacoes_pessoais/dados_bancarios/create',   to: 'dashboards/sellers/informations/banking#create'
  put 'dashboards/representantes/informacoes_pessoais/dados_bancarios/update',    to: 'dashboards/sellers/informations/banking#update'

  get 'dashboards/representantes/informacoes_pessoais/documentos',          to: 'dashboards/sellers/informations/documents#index'
  get 'dashboards/representantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/sellers/informations/documents#contract'
  get 'dashboards/representantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/sellers/informations/documents#distract'

  get 'dashboards/representantes/financeiro',        to: 'dashboards/sellers/finance/main#index'

  get 'dashboards/representantes/financeiro/vendas', to: 'dashboards/sellers/finance/sales#index'

  get 'dashboards/representantes/financeiro/recibos',                            to: 'dashboards/sellers/finance/receipts#index'
  post 'dashboards/representantes/financeiro/recibos/recibo_pagamento_autonomo', to: 'dashboards/sellers/finance/receipts#generate_receipt'

  get 'cameras/logins',                             to: 'cameras/logins#index'
  get 'cameras/logins/angels',                      to: 'cameras/logins#angels'
  get 'cameras/logins/motoristas',                  to: 'cameras/logins#drivers'
  get 'cameras/logins/driver_names',                to: 'cameras/logins#driver_names'
  post 'cameras/logins/validate_angels_access',     to: 'cameras/logins#validate_angels_access'
  post 'cameras/logins/validate_drivers_access',    to: 'cameras/logins#validate_drivers_access'

  get 'cameras/dashboards/passageiros', to: 'cameras/dashboards#passengers'

  get 'cameras/dashboards/motoristas',             to: 'cameras/dashboards/drivers#index'
  get 'cameras/dashboards/motoristas/login',       to: 'cameras/dashboards/drivers#login'
  get 'cameras/dashboards/motoristas/logout',      to: 'cameras/dashboards/drivers#logout'
  get 'cameras/dashboards/motoristas/qrcode',      to: 'cameras/dashboards/drivers#qrcode'
  get 'cameras/dashboards/motoristas/transmissao', to: 'cameras/dashboards/drivers#transmission'

  get 'cameras/dashboards/angels',             to: 'cameras/dashboards/angels#index'
  get 'cameras/dashboards/angels/login',       to: 'cameras/dashboards/angels#login'
  get 'cameras/dashboards/angels/logout',      to: 'cameras/dashboards/angels#logout'
  get 'cameras/dashboards/angels/transmissao', to: 'cameras/dashboards/angels#transmission'

app/controllers/cameras/dashboards/drivers_controller.rb
#TODO CRIAR OPÇÃO PARA O PASSAGEIRO MANDAR O LINK PARA O ANGEL E GERE O FEEDBACK PARA O MOTORISTA
class Cameras::Dashboards::DriversController < ApplicationController
  before_action :validate_driver_session, except: [:login]

  def index; end
  def transmission; end

  def qrcode
    @driver = Driver.find(session[:driver]['id'])
  end

  def login
    reset_session
  end

  def logout
    reset_session

    redirect_to cameras_dashboards_motoristas_login_path
  end
end

app/controllers/dashboards/subscribers/angels_controller.rb
class Dashboards::Subscribers::AngelsController < ApplicationController
  before_action :validate_sessions
  before_action :find_subscriber

  def index; end

  def insert
    @angel = Angel.new
  end

  def edit
    @angel = @subscriber.angels.detect { |angel| angel.id == params['angel'].to_i }
 
    unless @angel.present?
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.search_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.search_data_failed')
  end

  def remove
    angel = @subscriber.angels.detect { |angel| angel.id == params['angel'].to_i }

    if angel.present?
      angel.delete

      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.remove_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.remove_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.remove_data_failed')
  end

  def update
    angel = @subscriber.angels.detect { |angel| angel.id == params['angel_id'].to_i }

    if angel.update_attributes!(angel_params)
      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.update_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.save_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.save_data_failed')
  end

  def create
    angel = Angel.new(angel_params)

    if angel.valid?
      angel.save!

      redirect_to dashboards_assinantes_angels_path,
                  notice: I18n.t('messages.successes.save_data')
    else
      redirect_to dashboards_assinantes_angels_path,
                  alert: I18n.t('messages.errors.save_data_failed')
    end
  rescue
    redirect_to dashboards_assinantes_angels_path,
                alert: I18n.t('messages.errors.save_data_failed')
  end

  private

    def angel_params
      params
        .require(:angel)
        .permit(:name, :cpf, :status)
        .merge!({ subscriber: @subscriber })
    end
end

app/controllers/dashboards/subscribers/drivers_controller.rb
class Dashboards::Subscribers::DriversController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index
    @drivers = @subscriber.drivers
  end

  def insert
    @vehicles_list = @subscriber.vehicles.pluck(:license_plate)
    @driver = Driver.new
  end

  def remove
    if driver
      Driver.delete(driver.id)

      redirect_to dashboards_assinantes_motoristas_path,
                  notice: t('messages.successes.remove_data')
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.remove_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.remove_data_failed')
  end

  def edit
    @vehicles_list = @subscriber.vehicles.pluck(:license_plate)

    if driver
      @driver = driver
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.search_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.show_data_failed')
  end

  def details
    if driver
      @driver = driver
    else
      redirect_to dashboards_assinantes_motoristas_path,
                  alert: t('messages.errors.search_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.show_data_failed')
  end

  def create
    driver = Driver.new(driver_params)
    driver.code = driver.generate_code

    if driver.valid? && driver.save!
      driver.update_attributes!(vehicles: vehicles_list)
      driver.document.attach(driver_params['document'])
      driver.avatar.attach(driver_params['avatar'])

      redirect_to driver_details_path(driver.id),
                  notice: t('messages.successes.save_data')
    else
      redirect_to dashboards_assinantes_motoristas_adicionar_path,
                  alert: t('messages.errors.save_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_adicionar_path,
                alert: t('messages.errors.save_data_failed')
  end

  def update
    driver_data = driver

    if driver_data.update_attributes!(driver_params)
      driver_data.update_attributes!(vehicles: vehicles_list) if driver_params['vehicle_license_plates']
      driver_data.document.attach(driver_params['document']) if driver_params['document']
      driver_data.avatar.attach(driver_params['avatar']) if driver_params['avatar']

      redirect_to driver_details_path(driver_data.id),
                  notice: t('messages.successes.update_data')
    else
      redirect_to edit_driver_path(driver_data.id),
                  alert: t('messages.errors.update_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to dashboards_assinantes_motoristas_path,
                alert: t('messages.errors.update_data_failed')
  end

  private

    def vehicles_list
      params['driver']['vehicle_license_plates']
        .reject(&:blank?)
        .map { |license_plate| Vehicle.find_by_license_plate(license_plate) }
    end

    def driver
      driver_id = params['driver_id'] || driver_params[:id] || params['driver']['driver_id']

      driver ||= @subscriber
                   .drivers
                   .detect { |driver| driver.id.to_s == driver_id }
    end

    def driver_params
      params
        .require(:driver)
        .permit(:vehicle_license_plates,
                :name,
                :license,
                :paid_activity,
                :expedition_date,
                :expiration_date,
                :document,
                :avatar)
    end
end

app/controllers/dashboards/subscribers/informations/main_controller.rb
class Dashboards::Subscribers::Informations::MainController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index; end
end

app/controllers/dashboards/subscribers/main_controller.rb
class Dashboards::Subscribers::MainController < ApplicationController
  before_action :validate_sessions, :find_subscriber

  def index; end

  def logout
    reset_session

    redirect_to login_assinantes_path
  end
end

app/helpers/dashboards/subscribers_helper.rb
module Dashboards::SubscribersHelper
  def drivers_name(vehicle)
    vehicle
      .drivers
      .pluck(:name)
      .sort
      .join(' | ') 
  end
end

app/helpers/driver_helper.rb
module DriverHelper
  def rate(driver)
    "#{Rating.average(driver)}/#{Rating::DEFAULT_RATE}"
  end
end

app/views/dashboards/subscribers/drivers/edit.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.drivers'), dashboards_assinantes_motoristas_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.edit') %>
      </li>
    </ol>
  </nav>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <h3>
     <b><%= t('.title') %></b>
    </h3>
    <hr>
    <%= form_with scope: 'driver', url: dashboards_assinantes_motoristas_update_path, method: :put do |f| %>
      <div class="form-group">
        <label><%= t('.choose_a_vehicle') %></label>
        <%= f.select :vehicle_license_plates,
                     options_for_select(@vehicles_list, @driver.vehicles.pluck(:license_plate)),
                     {},
                     { multiple: true,
                       size: @subscriber.vehicles.size,
                       required: true,
                       class: 'form-control short-fields' } %>
      </div>      
      <div class="form-group">
        <label><%= t('.name') %></label>
        <%= f.text_field :name,
                         value: @driver.name,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.license') %></label>
        <%= f.text_field :license,
                         value: @driver.license,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-check">
        <%= f.check_box :paid_activity,
                        value: @driver.paid_activity,
                        class: 'form-check-input' %>
        <label class="form-check-label"><%= t('.paid_activity') %></label>
      </div>
      <br>
      <div class="form-group">
        <label><%= t('.expedition_date') %></label> 
        <%= f.text_field :expedition_date,
                         value: formatted_date(@driver.expedition_date),
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.expiration_date') %></label>
        <%= f.text_field :expiration_date,
                         value: formatted_date(@driver.expiration_date),
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label>
          <%= t('.avatar') %>
          <span class="small-text"><%= t('.line_2') %></span>
        </label>
        <%= f.file_field :avatar,
                         value: @driver.avatar,
                         class: 'form-control short-fields' %>
      </div>
      <%= image_tag @driver.avatar, class: 'photos' %>
      <br><br>
      <div class="form-group">
        <label>
          <%= t('.document') %>
          <span class="small-text"><%= t('.line_2') %></span>
        </label>
        <%= f.file_field :document,
                         value: @driver.document,
                         class: 'form-control short-fields' %>
      </div>
      <%= image_tag @driver.document, class: 'photos' %>
      <hr>
      <%= f.submit t('.update_data_btn'),
                   class: 'btn btn-primary' %>

      <%= f.hidden_field :driver_id, value: @driver.id %>
    <% end %>
    <br><br><br>
  </div>
</div>
<%= render './././partials/footer' %>

app/views/dashboards/subscribers/drivers/index.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.drivers') %>
      </li>
    </ol>
  </nav>
  <%= render './partials/messages' %>
  <%= link_to t('.add_driver_btn'), dashboards_assinantes_motoristas_adicionar_path, class: 'btn btn-primary btn-sm' %>
  <h4>
    <b><%= t('.drivers') %></b>
  </h4>
  <table class="table">
    <thead>
      <th><%= t('.name') %></th>
      <th><%= t('.cnh') %></th>
      <th><%= t('.paid_activity') %></th>
      <th><%= t('.associated_at') %></th>
      <th><%= t('.status') %></th>
      <th><%= t('.vehicles') %></th>
      <th></th>
    <thead>
    <% if @drivers.present? %>
      <% @drivers.each do |driver| %>
        <tr>
          <td><%= driver.name %></td>
          <td><%= driver.license %></td>
          <td><%= t("#{driver.paid_activity.to_s}") %></td>
          <td><%= convert_date(driver.created_at) %></td>
          <td><%= driver.status %></td>
          <td><%= driver.vehicles.pluck(:license_plate).join(' | ') %></td>
          <td>
          <%= link_to driver_details_path(driver.id) do %>
            <i class='material-icons'>view_headline</i>
          <% end %>
          <%= link_to edit_driver_path(driver), title: t('.edit_btn') do %>
            <i class='material-icons'>edit</i>
          <% end %>
          <%= link_to remove_driver_path(driver), method: :delete, title: t('.remove_btn') do %>
            <i class='material-icons'>delete_forever</i>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>
<%= render './././partials/footer' %>

app/views/dashboards/subscribers/drivers/insert.html.erb
<%= render './././partials/header' %>
<%= render './././partials/logout' %>
<div class="container-fluid">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to t('breadcrumbs.dashboards.subscribers.login'), login_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.dashboard'), dashboards_assinantes_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= link_to t('breadcrumbs.dashboards.subscribers.drivers'), dashboards_assinantes_motoristas_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= t('breadcrumbs.dashboards.subscribers.insert') %>
      </li>
    </ol>
  </nav>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <h3>
     <b><%= t('.title') %></b>
    </h3>
    <hr>
    <%= form_with scope: 'driver', url: dashboards_assinantes_motoristas_create_path do |f| %>
      <div class="form-group">
        <label><%= t('.choose_a_vehicle') %></label>
        <%= f.select :vehicle_license_plates,
                     options_for_select(@vehicles_list, ''),
                     {},
                     { multiple: true,
                       size: @vehicles_list.size,
                       required: true,
                       class: 'form-control short-fields' } %>
      </div>      
      <div class="form-group">
        <label><%= t('.name') %></label>
        <%= f.text_field :name,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.license') %></label>
        <%= f.text_field :license,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-check">
        <%= f.check_box :paid_activity,
                         class: 'form-check-input' %>
        <label class="form-check-label"><%= t('.paid_activity') %></label>
      </div>
      <br>
      <div class="form-group">
        <label><%= t('.expedition_date') %></label> 
        <%= f.text_field :expedition_date,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.expiration_date') %></label>
        <%= f.text_field :expiration_date,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label>
          <%= t('.license') %>
          <span class="small-text"><%= t('.line_1') %></span>
        </label>
        <%= f.file_field :document,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label>
          <%= t('.avatar') %>
          <span class="small-text"><%= t('.line_2') %></span>
        </label>
        <%= f.file_field :avatar,
                         class: 'form-control short-fields',
                         required: true %>
      </div>
      <br>
      <%= f.submit t('.save_data_btn'),
                   class: 'btn btn-primary' %>
    <% end %>
    <br><br><br>
  </div>
</div>
<%= render './././partials/footer' %>