config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount Heartcheck::App.new, at: '/monitoring'

  root 'home#index'

  get 'home/chart_data',               to: 'home#chart_data'
  get 'home/hire',                     to: 'home#hire'
  get 'home/contrato',                 to: 'home#contract'
  get 'home/representantes',           to: 'home#seller'
  get 'home/representantes/contratar', to: 'home#hire_seller'
  get 'home/representantes/contrato',  to: 'home#seller_contract'
  post 'home/representantes/create',   to: 'home#create_seller'

  get 'checkout/identificacao',                to: 'checkout#identification'
  get 'checkout/identificacao/assinante',      to: 'checkout#subscriber'
  get 'checkout/identificacao/novo_assinante', to: 'checkout#new_subscriber'
  get 'checkout/veiculos',                     to: 'checkout#vehicles'
  get 'checkout/resumo',                       to: 'checkout#resume'
  get 'checkout/subscriber_address',           to: 'checkout#subscriber_address'
  get 'checkout/check_seller',                 to: 'checkout#check_seller'
  get 'checkout/user_availability',            to: 'checkout#user_availability'
  get 'checkout/subscriber_ip',                to: 'checkout#subscriber_ip'
  get 'checkout/vehicle_model_list',           to: 'checkout#vehicle_model_list'
  get 'checkout/add_vehicles',                 to: 'checkout#add_vehicles'
  get 'checkout/pagamento',                    to: 'checkout#payment'
  get 'checkout/finalizacao',                  to: 'checkout#finalization'
  get 'checkout/remove_vehicles',              to: 'checkout#remove_vehicles'
  post 'checkout/subscriber_info',             to: 'checkout#subscriber_info'
  post 'checkout/process_payment',             to: 'checkout#process_payment'
  post 'checkout/find_subscriber_data',        to: 'checkout#find_subscriber_data'

  get 'login/assinantes',                         to: 'subscriber_logins#index'
  get 'login/assinantes/esqueci_minha_senha',     to: 'subscriber_logins#forgot_my_password'
  get 'login/representantes',                     to: 'seller_logins#index'
  get 'login/representantes/esqueci_minha_senha', to: 'seller_logins#forgot_my_password'
  post 'login/assinantes/validate_access',        to: 'subscriber_logins#validate_subscriber_access'
  post 'login/assinantes/send_password',          to: 'subscriber_logins#send_subscriber_password'
  post 'login/representantes/validate_access',    to: 'seller_logins#validate_seller_access'
  post 'login/representantes/send_password',      to: 'seller_logins#send_seller_password'

  get 'dashboards/assinantes',                  to: 'dashboards/subscribers/main#index'
  get 'dashboards/assinantes/logout',           to: 'dashboards/subscribers/main#logout'

  get 'dashboards/assinantes/angels/',          to: 'dashboards/subscribers/angels#index'
  get 'dashboards/assinantes/angels/adicionar', to: 'dashboards/subscribers/angels#insert'
  get 'dashboards/assinantes/angels/editar',    to: 'dashboards/subscribers/angels#edit'
  post 'dashboards/assinantes/angels/create',   to: 'dashboards/subscribers/angels#create'
  put 'dashboards/assinantes/angels/update',    to: 'dashboards/subscribers/angels#update'
  delete 'dashboards/assinantes/angels/remove', to: 'dashboards/subscribers/angels#remove'

  get 'dashboards/assinantes/chamados',                    to: 'dashboards/subscribers/tickets#index'
  get 'dashboards/assinantes/chamados/novo',               to: 'dashboards/subscribers/tickets#new'
  get 'dashboards/assinantes/chamados/:ticket_id',         to: 'dashboards/subscribers/tickets#show', as: 'show_ticket'
  get 'dashboards/assinantes/chamados/:ticket_id/editar',  to: 'dashboards/subscribers/tickets#edit', as: 'edit_ticket'
  post 'dashboards/assinantes/chamados/create',            to: 'dashboards/subscribers/tickets#create'
  post 'dashboards/assinantes/chamados/reopen/:ticket_id', to: 'dashboards/subscribers/tickets#reopen', as: 'reopen_ticket'

  get 'dashboards/assinantes/monitoramento', to: 'dashboards/subscribers/monitoring#index'

  get 'dashboards/assinantes/motoristas',                      to: 'dashboards/subscribers/drivers#index'
  get 'dashboards/assinantes/motoristas/adicionar',            to: 'dashboards/subscribers/drivers#insert'
  get 'dashboards/assinantes/motoristas/:driver_id/detalhes',  to: 'dashboards/subscribers/drivers#details', as: 'driver_details'
  get 'dashboards/assinantes/motoristas/:driver_id/editar',    to: 'dashboards/subscribers/drivers#edit', as: 'edit_driver'
  post 'dashboards/assinantes/motoristas/create',              to: 'dashboards/subscribers/drivers#create'
  put 'dashboards/assinantes/motoristas/update',               to: 'dashboards/subscribers/drivers#update'
  delete 'dashboards/assinantes/motoristas/:driver_id/remove', to: 'dashboards/subscribers/drivers#remove', as: 'remove_driver'

  get 'dashboards/assinantes/veiculos',                             to: 'dashboards/subscribers/vehicles#index'
  get 'dashboards/assinantes/veiculos/:vehicle_id/adicionar_fotos', to: 'dashboards/subscribers/vehicles#add_photos', as: 'add_vehicle_photos'
  get 'dashboards/assinantes/veiculos/:vehicle_id/detalhes',        to: 'dashboards/subscribers/vehicles#details', as: 'vehicle_details'
  post 'dashboards/assinantes/veiculos/upload_photos',              to: 'dashboards/subscribers/vehicles#upload_photos'

  get 'dashboards/assinantes/informacoes_pessoais',          to: 'dashboards/subscribers/informations/main#index'

  get 'dashboards/assinantes/informacoes_pessoais/cadastro',        to: 'dashboards/subscribers/informations/register#index'
  get 'dashboards/assinantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/subscribers/informations/register#edit'
  put 'dashboards/assinantes/informacoes_pessoais/cadastro/update', to: 'dashboards/subscribers/informations/register#update'

  get 'dashboards/assinantes/informacoes_pessoais/documentos',          to: 'dashboards/subscribers/informations/documents#index'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/subscribers/informations/documents#contract'
  get 'dashboards/assinantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/subscribers/informations/documents#distract'

  get 'dashboards/representantes',        to: 'dashboards/sellers/main#index'
  get 'dashboards/representantes/logout', to: 'dashboards/sellers/main#logout'

  get 'dashboards/representantes/informacoes_pessoais',                 to: 'dashboards/sellers/informations/main#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro',        to: 'dashboards/sellers/informations/register#index'
  get 'dashboards/representantes/informacoes_pessoais/cadastro/editar', to: 'dashboards/sellers/informations/register#edit'
  put 'dashboards/representantes/informacoes_pessoais/cadastro/update', to: 'dashboards/sellers/informations/register#update'

  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios',           to: 'dashboards/sellers/informations/banking#index'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/editar',    to: 'dashboards/sellers/informations/banking#edit'
  get 'dashboards/representantes/informacoes_pessoais/dados_bancarios/adicionar', to: 'dashboards/sellers/informations/banking#insert'
  post 'dashboards/representantes/informacoes_pessoais/dados_bancarios/create',   to: 'dashboards/sellers/informations/banking#create'
  put 'dashboards/representantes/informacoes_pessoais/dados_bancarios/update',    to: 'dashboards/sellers/informations/banking#update'

  get 'dashboards/representantes/informacoes_pessoais/documentos',          to: 'dashboards/sellers/informations/documents#index'
  get 'dashboards/representantes/informacoes_pessoais/documentos/contrato', to: 'dashboards/sellers/informations/documents#contract'
  get 'dashboards/representantes/informacoes_pessoais/documentos/distrato', to: 'dashboards/sellers/informations/documents#distract'

  get 'dashboards/representantes/financeiro',        to: 'dashboards/sellers/finance/main#index'

  get 'dashboards/representantes/financeiro/vendas', to: 'dashboards/sellers/finance/sales#index'

  get 'dashboards/representantes/financeiro/recibos',                            to: 'dashboards/sellers/finance/receipts#index'
  post 'dashboards/representantes/financeiro/recibos/recibo_pagamento_autonomo', to: 'dashboards/sellers/finance/receipts#generate_receipt'

  get 'cameras/logins',                             to: 'cameras/logins#index'
  get 'cameras/logins/angels',                      to: 'cameras/logins#angels'
  get 'cameras/logins/motoristas',                  to: 'cameras/logins#drivers'
  get 'cameras/logins/driver_names',                to: 'cameras/logins#driver_names'
  post 'cameras/logins/validate_angels_access',     to: 'cameras/logins#validate_angels_access'
  post 'cameras/logins/validate_drivers_access',    to: 'cameras/logins#validate_drivers_access'

  get 'cameras/dashboards/passageiros', to: 'cameras/dashboards#passengers'

  get 'cameras/dashboards/motoristas',             to: 'cameras/dashboards/drivers#index'
  get 'cameras/dashboards/motoristas/login',       to: 'cameras/dashboards/drivers#login'
  get 'cameras/dashboards/motoristas/logout',      to: 'cameras/dashboards/drivers#logout'
  get 'cameras/dashboards/motoristas/qrcode',      to: 'cameras/dashboards/drivers#qrcode'
  get 'cameras/dashboards/motoristas/transmissao', to: 'cameras/dashboards/drivers#transmission'

  get 'cameras/dashboards/angels',             to: 'cameras/dashboards/angels#index'
  get 'cameras/dashboards/angels/login',       to: 'cameras/dashboards/angels#login'
  get 'cameras/dashboards/angels/logout',      to: 'cameras/dashboards/angels#logout'
  get 'cameras/dashboards/angels/transmissao', to: 'cameras/dashboards/angels#transmission'

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def seller; end
  def hire_seller; end

  def hire
    session[:plan] = { code: params['plan']['code'],
                       name: params['plan']['name'],
                       price: params['plan']['price'] }

    redirect_to checkout_identificacao_path
  end

  def chart_data
    render json: CHART_DATA, status: :ok
  end

  def create_seller
    seller = Seller.new(seller_params)

    if seller.valid? && seller.save!
      redirect_to home_representantes_path,
                  notice: t('messages.successes.created_seller')
    else
      redirect_to home_representantes_contratar_path,
                  alert: t('messages.errors.save_data_failed')
    end
  rescue => error
    Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

    redirect_to home_representantes_contratar_path,
                alert: t('messages.errors.save_data_failed')
  end

  def seller_contract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.seller.contract.title'),
                             template: 'dashboards/sellers/informations/documents/contract.html.erb',
                             layout: 'seller_contract.html')
      end
    end
  end

  def contract
    respond_to do |format|
      format.pdf do
        render Documents
                 .render_pdf(filename: t('documents.subscriber.contract.title'),
                             template: 'dashboards/subscribers/informations/documents/contract.html.erb',
                             layout: 'subscriber_contract.html')
      end
    end
  end

  private
    def seller_params
      params
        .require(:new_seller)
        .permit(:name,
                :core_register,
                :expedition_date,
                :expiration_date,
                :password,
                :document,
                :cellphone,
                :email,
                :linkedin,
                :address,
                :number,
                :complement,
                :district,
                :city,
                :state,
                :postal_code)
        .merge!({ code: Seller.generate_code(params['new_seller']['document']),
                  password: Seller.generate_password })
   end
end

app/helpers/home_helper.rb
module HomeHelper
  def add_check(boolean)
    boolean == 'true' ? 'yes.svg' : 'no.svg'
  end

  def price(unit, cents)
    unit.to_f + (cents.to_f / 100)
  end
end

app/views/home/hire_seller.html.erb
<%= render './././partials/header' %>
<div class="container-fluid">
  <br><br><br><br><br>
  <%= render './partials/messages' %>
  <div class='col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12'>
    <h3>
     <b><%= t('.title') %></b>
    </h3>
    <hr>
    <%= form_with scope: 'new_seller', url: home_representantes_create_path do |f| %>
      <div>
        <h4 class="form-subtitle">
          <%= t('.subtitle.personal_data') %>
        </h4>
      </div>
      <hr>
      <div class="form-group">
        <label><%= t('.name') %></label>
        <%= f.text_field :name,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.document') %></label>
        <%= f.text_field :document,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <br>
      <div>
        <h4 class="form-subtitle">
          <%= t('subtitle.core') %>
        </h4>
      </div>
      <hr>
      <div class="form-group">
        <label><%= t('.core_register') %></label>
        <%= f.text_field :core_register,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.expedition_date') %></label>
        <%= f.text_field :expedition_date,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.expiration_date') %></label>
        <%= f.text_field :expiration_date,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <br>
      <div>
        <h4 class="form-subtitle">
          <%= t('.subtitle.address') %>
        </h4>
      </div>
      <hr>
      <div class="form-group">
        <label><%= t('.address') %></label>
        <%= f.text_field :address,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.number') %></label>
        <%= f.text_field :number,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.complement') %></label>
        <%= f.text_field :complement,
                         class: 'form-control medium-fields' %>
      </div>
      <div class="form-group">
        <label><%= t('.district') %></label>
        <%= f.text_field :district,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.city') %></label>
        <%= f.text_field :city,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.state') %></label>
        <br>
        <%= f.select :state,
                     options_for_select(States.all_names),
                     {},
                     class: 'form-control medium-fields',
                     required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.postal_code') %></label>
        <%= f.text_field :postal_code,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <br>
      <div>
        <h4 class="form-subtitle">
          <%= t('.subtitle.contact') %>
        </h4>
      </div>
      <hr>
      <div class="form-group">
        <label><%= t('.email') %></label>
        <%= f.text_field :email,
                         class: 'form-control',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.cellphone') %></label>
        <%= f.text_field :cellphone,
                         class: 'form-control medium-fields',
                         required: true %>
      </div>
      <div class="form-group">
        <label><%= t('.linkedin_url') %></label>
        <%= f.text_field :linkedin,
                         placeholder: t('.linkedin_placeholder'),
                         class: 'form-control',
                         required: true %>
      </div>
      <br>
      <%= f.submit t('.send_data_btn'),
                   class: 'btn btn-primary small-fields' %>
    <% end %>
    <br>
    <br>
    <br>
  </div>
</div>
<%= render './././partials/footer' %>

app/views/home/index.html.erb
<section id="header">
  <div id="logo">
    <%= image_tag 'logo.png' %>
  </div>
  <div id="menu">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link" href="#company" id="company_lnk"><%= t('.menu.company') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#benefits" id="benefits_lnk"><%= t('.menu.benefits') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#subscribe_now" id="subscribe_now_lnk"><%= t('.menu.sign_it') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#jobs" id="jobs_link"><%= t('.menu.jobs') %></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= t('.menu.control_panel') %></a>
        <div class="dropdown-menu">
          <%= link_to t('.menu.subscribers'), login_assinantes_path, class: 'dropdown-item' %>
          <br><br>
          <%= link_to t('.menu.angels'), cameras_dashboards_angels_login_path, class: 'dropdown-item' %>
          <br><br>
          <%= link_to t('.menu.drivers'), cameras_dashboards_motoristas_login_path, class: 'dropdown-item' %>
          <br><br>
          <%= link_to t('.menu.sellers'), login_representantes_path, class: 'dropdown-item' %>
        </div>
     </li>
    </ul>
  </div>
</section>
<section id="main_phrase">
  <h1><%= t('.main_phrase') %></h1>
</section>
<section id="main">
  <section id="home">
    <%= image_tag 'home.png' %>
  </section>
  <section id="company">
    <h1><%= t('.company.title') %></h1>
    <p><%= t('.company.text_1') %></p>
    <p><%= t('.company.text_2') %></p>
    <hr>
    <canvas id="violence_chart"></canvas>
    <%= link_to t('.company.chart_source'),
                t('.company.chart_data_link'),
                target: '_blank' %>
    <hr>
    <p><%= t('.company.text_3') %></p>
    <p><%= t('.company.text_4') %></p>
  </section>
  <section id="benefits">
    <h1><%= t('.benefits.title') %></h1>
    <br>
    <table class="table table-striped">
      <th><%= t('.benefits.benefit') %></th>
      <th><%= t('.benefits.driver') %></th>
      <th><%= t('.benefits.passenger') %></th>
      <tr>
        <td><%= t('.benefits.benefit_list.1.title') %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.1.driver')) %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.1.passenger')) %></td>
      </tr>
      <tr>
        <td><%= t('.benefits.benefit_list.2.title') %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.2.driver')) %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.2.passenger')) %></td>
      </tr>
      <tr>
        <td><%= t('.benefits.benefit_list.3.title') %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.3.driver')) %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.3.passenger')) %></td>
      </tr>
      <tr>
        <td><%= t('.benefits.benefit_list.4.title') %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.4.driver')) %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.4.passenger')) %></td>
      </tr>
      <tr>
        <td><%= t('.benefits.benefit_list.5.title') %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.5.driver')) %></td>
        <td><%= image_tag add_check(t('.benefits.benefit_list.5.passenger')) %></td>
      </tr>
    </table>
  </section>
  <section id="subscribe_now">
    <h1><%= t('.subscribe_now.title') %></h1>
    <div>
      <% PLAN_CONFIG[:plans][:data].each do |plan| %>
        <div>
          <div>
            <h2 class="plan_name">
              <span><%= t('.subscribe_now.plan') %></span><br>
              <span><%= plan[:name] %></span>
            </h2>
          </div>
          <div>
            <span class="line_through">
              <span class="old_price"><%= t('.subscribe_now.old_price', price: plan[:old_price]) %></span>
            </span>
          </div>
          <div class="current_price">
            <span>
              <sup><%= t('.subscribe_now.currency') %></sup>
              <span><%= plan[:current_price][:unit] %></span>
              <sup><%= t('.subscribe_now.separator', cents: plan[:current_price][:cents]) %></sup>
            </span>
            <sup class="periodicity"><%= t('.subscribe_now.periodicity') %></sup>
          </div>
          <%= link_to controller: 'home',
                      action: 'hire',
                      plan: { name: plan[:name],
                              price: price(plan[:current_price][:unit], plan[:current_price][:cents]),
                              code: plan[:code] } do %>
            <div class="hire"><%= t('.subscribe_now.hire') %></div>
          <% end %>
          <div class="features">
            <% plan[:features].sort.each do |feature| %>
              <span><%= feature %></span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </section>
  <section id="jobs">
    <h1><%= t('.jobs.title') %></h1>
    <p><%= t('.jobs.line') %></p>
    <p>
      <%= link_to t('.jobs.inform_your_data'), home_representantes_contratar_path, class: 'jobs_lnk' %>
      <br><br>
      <%= link_to t('.jobs.contract'), home_representantes_contrato_path(format: :pdf), targast: 'blank', class: 'jobs_contract_lnk' %>
    </p>
  </section>
  <section id="footer">
    <span><%= t('.social_medias.title') %></span>
    <div class="social_medias">
      <%= link_to APP_CONFIG[:social_medias][:facebook], target: '_blank', alt: t('.social_medias.facebook'), class: 'nav-link' do %>
        <%= image_tag 'facebook.png' %>
      <% end %>

      <%= link_to APP_CONFIG[:social_medias][:twitter], target: '_blank', alt: t('.social_medias.twitter'), class: 'nav-link' do %>
        <%= image_tag 'twitter.png' %>
      <% end %>

      <%= link_to APP_CONFIG[:social_medias][:instagram], target: '_blank', alt: t('.social_medias.instagram'), class: 'nav-link' do %>
        <%= image_tag 'instagram.png' %>
      <% end %>
    </div>
    <span><%= t('.footer.payment_methods') %></span>
    <div class="payment_methods">
      <div><%= image_tag 'american-express.svg', class: 'payment_methods_logo' %></div>
      <div><%= image_tag 'mastercard.svg', class: 'payment_methods_logo' %></div>
      <div><%= image_tag 'diners-club.svg', class: 'payment_methods_logo' %></div>
      <div><%= image_tag 'visa.svg', class: 'payment_methods_logo' %></div>
      <div><%= image_tag 'elo.svg', class: 'payment_methods_logo' %></div>
    </div>
    <div class="contract_link">
      <%= link_to t('.footer.contract'), home_contrato_path(format: :pdf), target: 'blank' %>
    </div>
    <div class="company_info">
      <p><%= t('.footer.company_info.line_1', current_year: DateTime.now.year) %></p>
      <p><%= t('.footer.company_info.line_2') %></p>
      <p><%= t('.footer.company_info.line_3') %></p>
    </div>
    <button type="button" class="btn btn-link sources_btn" data-toggle="modal" data-target="#source_modal">
      <%= t('.footer.fonts_images_btn') %>
    </button>
    <br><br>
  </section>
  <section>
    <div class="modal fade" id="source_modal" tabindex="-1" role="dialog" aria-labelledby="modal_title" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <p class="modal-title sources_title" id="modal_title"><%= t('.modal.title') %></p>
          </div>
          <div class="modal-body">
            <p>
              <%= t('.modal.image_source.label') %>
              <ul>
                <li><a href="<%= t('.modal.image_source.url.1') %>" target="_blank"><%= t('.modal.image_source.text.1') %></a></li>
                <li><a href="<%= t('.modal.image_source.url.2') %>" target="_blank"><%= t('.modal.image_source.text.2') %></a></li>
                <li><a href="<%= t('.modal.image_source.url.3') %>" target="_blank"><%= t('.modal.image_source.text.3') %></a></li>
              </ul>
            </p>
            <p>
              <%= t('.modal.icon_source.label') %>
              <ul>
                <li><a href="<%= t('.modal.icon_source.url.1') %>" target="_blank"><%= t('.modal.icon_source.text.1') %></a></li>
                <li><a href="<%= t('.modal.icon_source.url.2') %>" target="_blank"><%= t('.modal.icon_source.text.2') %></a></li>
                <li><a href="<%= t('.modal.icon_source.url.3') %>" target="_blank"><%= t('.modal.icon_source.text.3') %></a></li>
                <li><a href="<%= t('.modal.icon_source.url.4') %>" target="_blank"><%= t('.modal.icon_source.text.4') %></a></li>
                <li><a href="<%= t('.modal.icon_source.url.5') %>" target="_blank"><%= t('.modal.icon_source.text.5') %></a></li>
              </ul>
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-light" data-dismiss="modal"><%= t('.modal.close_btn') %></button>
          </div>
        </div>
      </div>
    </div>
  </section>
</section>
<%= render './././partials/footer' %>

app/views/home/seller.html.erb
<%= render './././partials/header' %>                                                                                                                                                     
<div class="container-fluid">
  <br><br><br><br><br>
  <%= render './partials/messages' %>
</div>